# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdDepthDists <- function(new_dists, dists, N1) {
    .Call(`_depthtestr_pdDepthDists`, new_dists, dists, N1)
}

lcdVariantDepthDists <- function(new_dists, dists, N1) {
    .Call(`_depthtestr_lcdVariantDepthDists`, new_dists, dists, N1)
}

lcdDepthDists <- function(new_dists, dists, N1) {
    .Call(`_depthtestr_lcdDepthDists`, new_dists, dists, N1)
}

